spring:
  application:
    name: test-sp-customer
  r2dbc:
    password: 123
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    #url: jdbc:postgresql://database:5432/postgres
    #username: postgres
    #password: postgres
    driverClassName: org.postgresql.Driver
    initialization-mode: always

server:
  port: 8093

logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG
        r2dbc: DEBUG

