-- Drop table

-- DROP TABLE public.person;

CREATE TABLE IF NOT EXISTS public.person (
	person_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	address varchar(255) NULL,
	age int4 NULL,
	gender varchar(255) NULL,
	identification varchar(255) NULL,
	full_name varchar(255) NULL,
	phone varchar(255) NULL,
	CONSTRAINT person_prkey PRIMARY KEY (person_id),
	CONSTRAINT uk_r5vsms84ih2viwd6tatk9o5pr UNIQUE (identification)
);


-- Drop table

-- DROP TABLE public.customer;

CREATE TABLE IF NOT EXISTS public.customer (
	customer_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	password varchar(255) NULL,
	status bool NULL,
	person_id int4 NOT NULL,
	CONSTRAINT customer_prkey PRIMARY KEY (customer_id),
	CONSTRAINT uk_nhdbltv7dnhp65s6wjb411gor UNIQUE (customer_id),
	CONSTRAINT fkgdh25m0u6r4xr9iuqnsbbh12q FOREIGN KEY (person_id) REFERENCES public.person(person_id)
);