openapi: 3.0.0
info:
  title: API Accounts - Movements.
  description: Service for the accounts and movements entity.
  contact:
    email: oscar.sarcoss@outlook.com
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /accounts:
    get:
      tags:
        - Accounts
      summary: Consult list of accounts
      description: Consult list of accounts.
      operationId: GetAccounts
      responses:
        '200':
          description: OK
          content:
            application/json; charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetAccountsResponse'
        '400':
          description: Bad Request
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      tags:
        - Accounts
      summary: Create new account
      description: Create new account.
      operationId: PostAccount
      requestBody:
        content:
          application/json; charset=UTF-8:
            schema:
              $ref: '#/components/schemas/PostAccountRequest'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/PostAccountResponse'
        '400':
          description: Bad Request
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /accounts/{accountId}:
    delete:
      tags:
        - Accounts
      summary: Delete account by ID
      description: Delete account by ID.
      operationId: DeleteAccount
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - Accounts
      summary: Update account by ID
      description: Update account by ID.
      operationId: PutAccountById
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Cliente
        content:
          application/json; charset=UTF-8:
            schema:
              $ref: '#/components/schemas/PutAccountByIdRequest'
        required: true
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /movements:
    get:
      tags:
        - Movements
      summary: Consult list of movements
      description: Consult list of movements.
      operationId: GetMovements
      responses:
        '200':
          description: OK
          content:
            application/json; charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetMovementsResponse'
        '400':
          description: Bad Request
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      tags:
        - Movements
      summary: Create new movement
      description: Create new movement.
      operationId: PostMovement
      requestBody:
        content:
          application/json; charset=UTF-8:
            schema:
              $ref: '#/components/schemas/PostMovementRequest'
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/PostMovementResponse'
        '400':
          description: Bad Request
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /statement-accounts:
    get:
      tags:
        - Statement Account
      summary: Consult statement account of customer by parameters
      description: Consult statement account of customer by parameters.
      operationId: GetStatementAccountByFilter
      parameters:
        - name: identification
          in: query
          description: Document number customer
          required: true
          schema:
            type: string
            maxLength: 13
            minLength: 10
            pattern: "^[0-9]{10,13}$"
            example: 099999999999
        - name: dateRange
          in: query
          description: Date range
          required: true
          schema:
            type: string
            pattern: "^[0-9]{2}/[0-9]{2}/[0-9]{4};[0-9]{2}/[0-9]{2}/[0-9]{4}$"
            example: "01/01/2025;31/01/2025"
      responses:
        '200':
          description: OK
          content:
            application/json; charset=UTF-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetStatementAccountByFilterResponse'
        '400':
          description: Bad Request
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Not Found
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal Server Error
          content:
            application/json; charset=UTF-8:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    PostAccountRequest:
      required:
        - accountNumber
        - accountType
        - initialBalance
        - status
        - customerId
      type: object
      properties:
        accountNumber:
          maxLength: 20
          minLength: 10
          pattern: "^[0-9]+$"
          type: string
        accountType:
          type: string
          enum: [AHORRO, CORRIENTE]
        initialBalance:
          type: number
          format: double
          minimum: 0
        status:
          type: boolean
        customerId:
          type: string
          format: uuid
    PostAccountResponse:
      properties:
        accountId:
          type: string
          format: uuid
    PutAccountByIdRequest:
      required:
        - accountNumber
        - accountType
        - initialBalance
        - status
      type: object
      properties:
        accountNumber:
          maxLength: 20
          minLength: 10
          pattern: "^[0-9]+$"
          type: string
        accountType:
          type: string
          enum: [AHORRO, CORRIENTE]
        initialBalance:
          type: number
          format: double
          minimum: 0
        status:
          type: boolean
    PostMovementRequest:
      required:
        - dateMovement
        - movementType
        - amount
        - accountId
      type: object
      properties:
        dateMovement:
          type: string
          format: date
        movementType:
          type: string
          enum: [DEPOSITO, RETIRO]
        amount:
          type: number
          format: double
          minimum: 0.01
        balance:
          type: number
          format: double
        accountId:
          type: string
          format: uuid
    PostMovementResponse:
      properties:
        movementId:
          type: string
          format: uuid
    GetAccountsResponse:
      type: object
      properties:
        accountId:
          type: string
          format: uuid
        accountNumber:
          type: string
        accountType:
          type: string
          enum: [AHORRO, CORRIENTE]
        initialBalance:
          type: string
        status:
          type: boolean
        fullName:
          type: string
    GetMovementsResponse:
      type: object
      properties:
        dateMovement:
          type: string
          format: date
        accountNumber:
          type: string
        movementType:
          type: string
          enum: [DEPOSITO, RETIRO]
        amount:
          type: number
          format: double
        balance:
          type: number
          format: double
    GetStatementAccountByFilterResponse:
      type: object
      properties:
        dateMovement:
          type: string
          format: date
        fullName:
          type: string
        accountNumber:
          type: string
        accountType:
          type: string
          enum: [AHORRO, CORRIENTE]
        initialBalance:
          type: number
          format: double
        status:
          type: boolean
        amountMovement:
          type: number
          format: double
        availableBalance:
          type: number
          format: double
    ErrorDetail:
      type: object
      properties:
        message:
          type: string
        businessMessage:
          type: string

    ErrorResponse:
      type: object
      properties:
        code:
          type: string
        detail:
          type: string
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetail'